source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem 'pg'

group :test, :development do
  gem "rspec-rails", "~> 2.0"

  gem 'spork-rails'
  gem 'watchr'
  gem 'factory_girl_rails'
  gem 'simplecov', :require => false
  gem 'shoulda-matchers'
end

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

