source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem 'pg'

gem 'haml-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem "therubyracer"
  gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS

  gem 'uglifier', '>= 1.0.3'
  gem 'jquery-ui-rails'
end

group :test, :development do
  gem 'spork-rails'
  gem "rspec-rails", "~> 2.0"
  gem 'factory_girl_rails'
end

group :test do
  gem 'watchr'
  gem 'simplecov', :require => false
  gem 'shoulda-matchers'
  gem 'sqlite3'
end

gem 'jquery-rails'
gem "twitter-bootstrap-rails"

gem "twitter"
gem 'omniauth-twitter'

gem "strong_parameters"

gem "simpleconfig"
gem 'will_paginate'
gem 'bootstrap-will_paginate'

gem "audited-activerecord", "~> 3.0"
