require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FacebookPostsController do

  # This should return the minimal set of attributes required to create a valid
  # FacebookPost. As you add validations to FacebookPost, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "account_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FacebookPostsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all facebook_posts as @facebook_posts" do
      facebook_post = FacebookPost.create! valid_attributes
      get :index, {}, valid_session
      assigns(:facebook_posts).should eq([facebook_post])
    end
  end

  describe "GET show" do
    it "assigns the requested facebook_post as @facebook_post" do
      facebook_post = FacebookPost.create! valid_attributes
      get :show, {:id => facebook_post.to_param}, valid_session
      assigns(:facebook_post).should eq(facebook_post)
    end
  end

  describe "GET new" do
    it "assigns a new facebook_post as @facebook_post" do
      get :new, {}, valid_session
      assigns(:facebook_post).should be_a_new(FacebookPost)
    end
  end

  describe "GET edit" do
    it "assigns the requested facebook_post as @facebook_post" do
      facebook_post = FacebookPost.create! valid_attributes
      get :edit, {:id => facebook_post.to_param}, valid_session
      assigns(:facebook_post).should eq(facebook_post)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FacebookPost" do
        expect {
          post :create, {:facebook_post => valid_attributes}, valid_session
        }.to change(FacebookPost, :count).by(1)
      end

      it "assigns a newly created facebook_post as @facebook_post" do
        post :create, {:facebook_post => valid_attributes}, valid_session
        assigns(:facebook_post).should be_a(FacebookPost)
        assigns(:facebook_post).should be_persisted
      end

      it "redirects to the created facebook_post" do
        post :create, {:facebook_post => valid_attributes}, valid_session
        response.should redirect_to(FacebookPost.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved facebook_post as @facebook_post" do
        # Trigger the behavior that occurs when invalid params are submitted
        FacebookPost.any_instance.stub(:save).and_return(false)
        post :create, {:facebook_post => { "account_id" => "invalid value" }}, valid_session
        assigns(:facebook_post).should be_a_new(FacebookPost)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FacebookPost.any_instance.stub(:save).and_return(false)
        post :create, {:facebook_post => { "account_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested facebook_post" do
        facebook_post = FacebookPost.create! valid_attributes
        # Assuming there are no other facebook_posts in the database, this
        # specifies that the FacebookPost created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FacebookPost.any_instance.should_receive(:update_attributes).with({ "account_id" => "1" })
        put :update, {:id => facebook_post.to_param, :facebook_post => { "account_id" => "1" }}, valid_session
      end

      it "assigns the requested facebook_post as @facebook_post" do
        facebook_post = FacebookPost.create! valid_attributes
        put :update, {:id => facebook_post.to_param, :facebook_post => valid_attributes}, valid_session
        assigns(:facebook_post).should eq(facebook_post)
      end

      it "redirects to the facebook_post" do
        facebook_post = FacebookPost.create! valid_attributes
        put :update, {:id => facebook_post.to_param, :facebook_post => valid_attributes}, valid_session
        response.should redirect_to(facebook_post)
      end
    end

    describe "with invalid params" do
      it "assigns the facebook_post as @facebook_post" do
        facebook_post = FacebookPost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FacebookPost.any_instance.stub(:save).and_return(false)
        put :update, {:id => facebook_post.to_param, :facebook_post => { "account_id" => "invalid value" }}, valid_session
        assigns(:facebook_post).should eq(facebook_post)
      end

      it "re-renders the 'edit' template" do
        facebook_post = FacebookPost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FacebookPost.any_instance.stub(:save).and_return(false)
        put :update, {:id => facebook_post.to_param, :facebook_post => { "account_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested facebook_post" do
      facebook_post = FacebookPost.create! valid_attributes
      expect {
        delete :destroy, {:id => facebook_post.to_param}, valid_session
      }.to change(FacebookPost, :count).by(-1)
    end

    it "redirects to the facebook_posts list" do
      facebook_post = FacebookPost.create! valid_attributes
      delete :destroy, {:id => facebook_post.to_param}, valid_session
      response.should redirect_to(facebook_posts_url)
    end
  end

end
