development:
  adapter: postgresql
  host: localhost
  database: dev_social
  username: dev1
  password: dfg233

test:
  adapter:  postgresql
  host:     localhost
  database: dev_social
  username: dev1
  password: dfg233

production:
  adapter:  postgresql
  host:     localhost
  database: dev_social
  username: dev1
  password: dfg233
