source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'jquery-rails'
gem 'bootstrap-sass', '2.0.4'
gem 'dalli'


# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

group :development, :test do
  gem 'rspec-rails'
end

group :test do
    if RUBY_PLATFORM =~ /(win32|w32)/
        gem "win32console", '1.3.0'
    end
    gem "minitest"
    gem "minitest-reporters", '< 0.8.0'
  gem 'capybara', '1.1.2'
  gem 'factory_girl_rails'
  gem 'headless'
  gem 'database_cleaner'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby
  gem 'turbo-sprockets-rails3'
  gem 'uglifier', '>= 1.0.3'
end

# Twitter integration
gem 'twitter'
gem 'twitter-text'
gem 'omniauth-twitter'
