source 'https://rubygems.org'

#gem 'rails', '= 3.2.14'
gem 'rails', '>= 4'
gem 'pg'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
gem 'unicorn'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'
#gem 'active_enum', '~> 0.9.12'
gem 'active_enum', git: 'git@github.com:adzap/active_enum.git'
gem 'haml-rails'
gem 'simple_form'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :assets do
  gem 'jquery-rails'
  gem 'uglifier', '>= 1.0.3'
  gem 'turbo-sprockets-rails3'
  gem 'sass-rails'
  gem 'bootstrap-sass-rails'
  gem 'angularjs-rails'
end

group :development do
  gem 'better_errors', '~> 0.8.0'
  gem 'rspec-rails'
  gem 'binding_of_caller'
  gem 'quiet_assets'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
